src/main/java/seedu/navi/Navi.java, src/main/java/seedu/navi/canteenfinder/nus/NUS.java, src/main/java/seedu/navi/canteenfinder/nus/landmark/Faculty.java, src/main/java/seedu/navi/canteenfinder/nus/landmark/Landmark.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
Change Building class to Faculty
Resolve checkstyle errors
=> Remove Canteen List from NUS

.gitignore, src/main/java/seedu/navi/canteenfinder/nus/landmark/CanteenStallPair.java, src/main/java/seedu/navi/canteenfinder/nus/landmark/Faculty.java, src/main/java/seedu/navi/canteenfinder/nus/landmark/Landmark.java, src/main/java/seedu/navi/canteenfinder/nus/landmark/canteen/Canteen.java, src/main/java/seedu/navi/canteenfinder/nus/landmark/canteen/stall/Stall.java, src/main/java/seedu/navi/canteenfinder/nus/landmark/canteen/stall/StallCharacteristic.java
Extracted the information from canteen.txt, and landmark.txt, storing the data in a hashmap.
Fixed the errors which caused merge checks to fail
=> Branch loading file

src/test/java/seedu/navi/NaviTest.java
=> Updated Junit testcase

build.gradle, src/main/java/seedu/navi/canteenfinder/CanteenFinder.java, src/main/java/seedu/navi/canteenfinder/landmark/canteen/stall/StallCharacteristic.java, src/main/java/seedu/navi/textui/TextUi.java
Add assertions in canteenfinder
=> Enable assertions in build.gradle

src/main/java/seedu/navi/Navi.java, src/main/java/seedu/navi/budget/Budget.java, src/main/java/seedu/navi/budget/BudgetParser.java
Fixes #32 
-add budget package with classes: budget and budgetparser -add budget for the day
-deduct expenses for the day
-view money spent daily and monthly, budget left for the day
=> Add budget feature to track expenses

src/main/java/seedu/navi/budget/Budget.java, src/test/java/seedu/navi/budget/BudgetTest.java
BudgetTest: Edit to follow the assertions of budget class
- Added getter methods with assertions to ensure non-negative values for daily budget, expenses, and monthly total.
- Included input validation to handle negative values and insufficient budget scenarios.
- Added logging for budget changes and expense tracking.
=> Budget class: Add assertions, logging and exceptions

data/faculty.txt, data/hostel.txt, data/otherbuilding.txt, src/main/java/seedu/navi/canteenfinder/landmark/Landmark.java, src/main/java/seedu/navi/storage/Storage.java, src/test/java/seedu/navi/storage/StorageTest.java, testdata/faculty.txt, testdata/hostel.txt, testdata/otherbuilding.txt
Added code in Storage.java to read distance from canteen and store in hashmaps.
Added Junit tests in Storagetest.java to test that distance is read and stored appropriately.
Added getter and setter functions in Landmark.java
=> Branch distance add

src/main/java/seedu/navi/budget/Budget.java, src/main/java/seedu/navi/budget/BudgetParser.java, src/test/java/seedu/navi/budget/BudgetTest.java
-removed logging as it wasnt neccessary
-added catch in budgetparser to catch my exceptions in budget -added line seperators before and after my output
=> Budgetparser: add line seperators for my output. Budget: remove logging

budget_data.json, src/main/java/seedu/navi/budget/Budget.java, src/main/java/seedu/navi/budget/BudgetParser.java, src/test/java/seedu/navi/budget/BudgetTest.java
-save and load data
-replaced daily budget with weekly budget
-added weeklyexpenses
-added option to carry over last weeks remaining budget
=> Add improvements to Budget feature

docs/DeveloperGuide.md
Edited the DG portion on Storage.java
=> Edited the DG portion on Storage.java

src/main/java/seedu/navi/favorites/Favorites.java, src/test/java/seedu/navi/favorites/FavoritesTest.java
- Implemented methods to save and load favorite items to/from a file using ObjectOutputStream and ObjectInputStream.
- Favorites are now persisted even after exiting the feature.
=> feat(storage): Add file-based persistence for favorite items

.gitignore, budget_data.json, src/main/java/seedu/navi/Navi.java
Add favorites.dat to gitignore
=> Resolve checkstyle errors

src/main/java/seedu/navi/canteen/canteenlookup/CanteenSearch.java, src/main/java/seedu/navi/canteen/storage/CanteenDataProcessor.java, src/main/java/seedu/navi/canteen/storage/FacultyDataProcessor.java, src/main/java/seedu/navi/canteen/storage/HostelDataProcessor.java, src/main/java/seedu/navi/canteen/storage/OtherBuildingDataProcessor.java, src/main/java/seedu/navi/canteen/storage/Storage.java
Changed storage of canteen/hostel/buildings/faculty information to ArrayList instead of reading from txt file
=> Branch redo storage

src/main/java/seedu/navi/favorites/Favorites.java, src/test/java/seedu/navi/favorites/FavoritesTest.java
- Added more test cases for edge cases and validation.
- Improved `undoRemove()` tests to ensure correct restoration order.
- Refactored `sortFavorites()` tests to verify both ascending and descending sorting.
- Strengthened `searchFavorites()` tests to check case-insensitive matching.
- Ensured `viewFavorites()` correctly handles empty and populated lists.
- General improvements in assertions and output verification.
=> Enhance FavoritesTest with comprehensive test cases

docs/DeveloperGuide.md
- Updated the Developer Guide to reflect the implementation of persistent storage.
- Modified data structures section to include persistent storage.
- Updated key operations to mention saving/loading of favorites.
- Revised system behavior to highlight automatic storage.
=> docs: update Developer Guide to include persistent storage details

docs/team/keerthanabanukumar.md
- Documented contributions to the development of the Navi CLI application.
- Highlighted key features implemented, including the Favorites feature, undo functionality, and command-line parser.
- Provided detailed descriptions of code, documentation, and team contributions.
=> Add Project Portfolio Page

.gitignore, src/main/java/seedu/navi/budget/Budget.java, src/main/java/seedu/navi/budget/BudgetParser.java
changed logic of finding if its a new week, to reset weekly budget and weekly expenses
=> Edit budget class

src/main/java/seedu/navi/budget/Budget.java, src/test/java/seedu/navi/budget/BudgetTest.java
=> fix issue 122 in budget, there was mistake in error message

src/main/java/seedu/navi/budget/BudgetParser.java
-removed emojies from all outputs as they are not recognised in java
-handled different type of errors and ensure the error message is accurate (when amount is blank, negative, non-number, exceed double limit)
fixes #136 
fixes #144 
fixes #145
=> Fix errors in budget feature regarding exceptions and error output messages 

docs/UserGuide.md
Increase clarity on how to enter canteen's sub-features
=> Standarise some instruction

src/main/java/seedu/navi/favorites/Favorites.java, src/main/java/seedu/navi/favorites/FavoritesParser.java
=> Remove all emojis

src/main/java/seedu/navi/Navi.java, src/main/java/seedu/navi/favorites/FavoritesParser.java
=> Fix white space invalid command issue

src/main/java/seedu/navi/favorites/FavoritesParser.java
=> Fix invalid number error message

src/main/java/seedu/navi/favorites/FavoritesParser.java
Fixes #124 
Fixes #139 
Fixes #126
=> Fix all add favorites bugs

src/main/java/seedu/navi/favorites/Favorites.java
=> Fix search command errors

src/main/java/seedu/navi/canteen/storage/DataRetriever.java, src/main/java/seedu/navi/exceptions/InvalidCanteenDataException.java, src/test/java/seedu/navi/canteenfinder/CanteenMainFinderTest.java
Added InvalidCanteenDataException
=> Edited the testcase and order of Canteen in DataRetriever.java.

src/main/java/seedu/navi/favorites/FavoritesParser.java
=> Fix duplicate entries

docs/DeveloperGuide.md, docs/UserGuide.md
Fixes #177 
Fixes #176 
Fixes #152 
Fixes #148 
Fixes #143
=> Fix DG and UG

docs/DeveloperGuide.md
=> Add user stories for v2.0

docs/DeveloperGuide.md, src/main/java/seedu/navi/textui/CanteenFinderTextUi.java
Update DG instructions for manual testing
=> Fix DG formatting
